### PR TITLE
Remove -gc, -property from man; add h|help

### PR DESCRIPTION
**Pull request by Geod24**
This was forgotten in #8.

TBH @ibuclaw this script could use an overhaul

### CODE REVIEW

**Comment by ibuclaw** [comment]
@Geod24 yeah, it's been on the cards for at least 5 years now.

**Comment by ibuclaw** [comment]
e.g https://github.com/D-Programming-GDC/gdmd/tree/dport

**Comment by Geod24** [comment]
That looks like a lot of work. Is there any hope it'll be finished ?
Note: I only plan to package gdmd for Alpine Linux, so the current state is okay-ish to me.

**Comment by ibuclaw** [comment]
Well, as I said, dmd/cli.d looks like a good candidate for replacing - it's a leaf module, so perfect for using as a library.  Although its intended purpose is for generating --help information, I think there's more than enough information there to use it as an option parser, and using upstream dmd directly is the best way to ensure that we always remain in sync with the current front-end options.

**Pull request merged**
